language: python
python:
- 3.6
- 2.7
cache: pip
env:
  - HOME=/home/travis
install:
  - pip install -U tox-travis
  - gem install jekyll -v 2.4.0
  - gem install s3_website
before_script:
  - createdb judicious
  - pip install --upgrade pip
script:
  - tox
  - cd docs; jekyll build; cd ..
after_success:
  - cd docs; s3_website push; cd ..
deploy:
  - provider: heroku
    true:
      python: 3.6
    api_key:
      secure: eHThgwNQRymA2xbukQ1/e543vVUYs4Hm125KOhCUO1elusNkHZUrR/2CzhYP8u8QRSaZF9ctf0Vgz/5K0PF3WkAsldnuGFhgFgrUJmnmauBJCpFFi1GdYh4HyXAgX0uo9KkxUUjbcA4Cpvuhfg3VaP12ZB5ocn3m56MvnOhg7ld07/qIMNhosO+IvHurgT2FBM4kgZbjqWKRsqumyjmdG5cZB9XwJJ3ws0EgmzN9P/EX68qdPOWo7Q/Hy7zb7MSOJVC6CWCskpAXAXdc78et+To3JUA/+rZ/v40IFN3fyt2xGCBGZPrWeNhrhfPvlxcPnQAhyXx11CGmXX4iqgfMaCHmHIWibNaAfdYwCUDYWmKvxy3X5Byqebtc+laj+iUuhwdrdnufYXDt83y18a75ZtA9dMK/7jmdyu3cyxG+jldX+joduU44fTG6oIG1uBvYSuIxGWJNQUZ13ZU4Fo7ei10XSAafRuYVv2gIaMzczNX2g9WtW926HHcRz3sTYdwYAHn8+Tv1k6U488bNtUxjUwZKeVUhQC79u2b37n0ghoz5iZxaZV3/lCnIjBHSC8ZDOeE5Tty+XthhWkMXqLEP80fW0OYg3ImrGtTxJDs2N91d7jKvQeA5MnWQVmMOYIDJowJzHXaXGy4k3IImJQxk5icF3m9zhN1aopuh/FShRoA=
    app: imprudent
  - provider: pypi
    user: suchow
    true:
       python: 3.6
       repo: suchow/judicious
       tags: true
    distributions: sdist bdist_wheel
    password:
      secure: U53L/lZTXu+9Ag+yzLyHZVj14lxmsBXsT5cJFtJZqrtLgxkBS2iHpFlCJ1x1kowfgJySR+91tbSsJ4akJAzjLLG56F9vQqtEEYsNeFfwnZTwdGYSPKZ8WsnQprCUtMwOlFY1V+oPrTFOtTAim77y000ClscSWxEO4/Q7o10KYSfEhuLdnUkEO/7gzFIo0YC0ACAHpirRnaIWLFGuXxnUk2zyf1k/zmNWm74pQwvNWDothbtXCP8wP3zaR+Ah6z0XqpLvqX1djW+sJFovat9E8RuvTQSe+111n+DEC2ODoSpFfC68MR429cpzIlx02ZePX7Ul0U0/Sbo1XNY+/pvBCmJ9Pl0P9g1zL6J0/lD1yIrppimN+Fi1r3oShmOMDora0QH/yyKKNhIVe2iTTUVgxw/l/X47QFCgUTRvHyMi4c3ZA1mOPF+i7wwB93KihtlMKZYT9fU097KY80EIkr27CS/mEUhmvlBCx2ATaCWs1ev/igjDwIHKURQT2+gHVCecQMG+qnhzTWIgQN+/UfZJX42kqAMNTI53KrIJNJH9JjTzbt8rgXX+WkFW8UcWNxf2DVYxn67cfUpq9GX17uGTj87E7Qp546iF57/HyK+465Sn7hcf8LRWt+HQJA1+riJ1FCku+g4bTUYEd1shKTW1qH5P+pcB5BbngARuUP0wC0A=
